Added Maven-surefire-plugin to file pom.xml . Created file run_test.y…
JR-Abstract/reddit-clone-abstract pull request #41
Opened 2024-02-29 09:21 UTC by ViktorKapustianyk

This workflow will run tests on every push to our repository.

2024-02-29 10:05 UTC, ViktorKapustianyk commented
Think that everything is added correctly but even can't build the product. It shows me the issue in the interface UserMapper

2024-02-29 10:45 UTC, oleksandr-jr commented
@ViktorKapustianyk Take a look at the latest commit here #40 and pull it

2024-02-29 10:51 UTC, oleksandr-jr commented
@ViktorKapustianyk I just merged the fix for you. You have to pull the changes locally

2024-02-29 10:55 UTC, oleksandr-jr requested changes

2024-02-29 10:55 UTC, oleksandr-jr commented on .github/workflows/run_tests.yml
> +        if: always()
I think we can remove this.

2024-02-29 21:02 UTC, ViktorKapustianyk commented
Please check now. Hope it's ok. I didn't know on which branch I had to make changes.

2024-03-01 11:32 UTC, oleksandr-jr approved these changes
@Opanasenko-Mykhailo Good job!

2024-03-05 20:08 UTC, merged